services:
  - type: web
    name: my-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_site.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: my_site.settings
      - key: SECRET_KEY
        value: django-insecure-f@irime@*y6%9$)j4xh*1e#x!-cm+&ren6b+^1v#ldyj=ca37!
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: https://anish0ms-site.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        value: drnrw0sqq
      - key: CLOUDINARY_API_KEY
        value: 773439715866931
      - key: CLOUDINARY_API_SECRET
        value: RqXN6KB5O5iY2yXeB0hlEijdExs